#!/usr/bin/env perl

$pdf_mode   = 4; # Use pdflua
$latex      = 'lualatex'.
              ' -synctex=1'.
              ' -file-line-error'.
              ' -halt-on-error'.
              ' -interaction=batchmode'.
              ' %S';
$max_repeat = 5;